#pragma once
#include "MailStore.hpp"
#include "Message.hpp"
#include "MailStoreTransaction.hpp"
#include "SyncException.hpp"
#include <functional>
#include <set>

namespace ReplyHeaders {
// MailCore adds the angle brackets itself. Never lowercase opaque Message-IDs,
// and never put a provider UID or SummerMail's placeholder on the wire.
inline std::string canonical(std::string id) {
    const auto first = id.find_first_not_of(" \t");
    if (first == std::string::npos) return "";
    id = id.substr(first, id.find_last_not_of(" \t") - first + 1);
    if (id.size() > 2 && id.front() == '<' && id.back() == '>') id = id.substr(1, id.size() - 2);
    if (id.find('@') == std::string::npos || id.find_first_of("<>\r\n\t ") != std::string::npos) return "";
    return id;
}

inline void apply(mailcore::MessageHeader * outgoing, Message & draft, MailStore * store,
                  bool smarterMail, const std::function<mailcore::MessageHeader *(Message *)> & fetch,
                  bool canFetch = true) {
    const std::string localId = draft._data.count("replyToMessageId") && draft._data["replyToMessageId"].is_string()
        ? draft._data["replyToMessageId"].get<std::string>() : "";
    const std::string captured = draft.replyToHeaderMessageId();
    if (localId.empty() && captured.empty()) return; // new mail or forward
    auto parent = localId.empty() ? nullptr : store->find<Message>(Query()
        .equal("accountId", draft.accountId()).equal("id", localId));
    if (!parent && !captured.empty()) parent = store->find<Message>(Query()
        .equal("accountId", draft.accountId()).equal("headerMessageId", captured));
    std::string mid = canonical(parent ? parent->headerMessageId() : captured);
    nlohmann::json refs = parent ? parent->_data.value("references", nlohmann::json()) : nlohmann::json();
    std::string irt = parent ? canonical(parent->replyToHeaderMessageId()) : "";
    if (canFetch && parent && (mid.empty() || parent->_data.value("headerMessageIdGenerated", false) ||
                   !refs.is_array() || (smarterMail && !parent->_data.value("smHydratedV1", false)))) {
        // One physical parent, not a thread scan. Old IMAP cache rows never
        // stored References; SmarterMail list rows may have synthetic IDs.
        auto header = fetch(parent.get());
        if (!header || header->isMessageIDAutoGenerated() || !header->messageID()) {
            throw SyncException("reply-headers-unavailable", "Cannot verify the original reply headers. Refresh the original message and try again; no email was sent.", false);
        }
        mid = canonical(header->messageID()->UTF8Characters());
        refs = nlohmann::json::array();
        if (header->references()) for (unsigned int i = 0; i < header->references()->count(); ++i) {
            refs.push_back(((mailcore::String *)header->references()->objectAtIndex(i))->UTF8Characters());
        }
        irt = "";
        if (header->inReplyTo() && header->inReplyTo()->count() == 1)
            irt = canonical(((mailcore::String *)header->inReplyTo()->objectAtIndex(0))->UTF8Characters());
        if (!mid.empty()) {
            MailStoreTransaction transaction{store, "reply headers"};
            // Network I/O may overlap a move/read action. Update only header
            // metadata on a freshly loaded row, never restore stale flags.
            auto current = store->find<Message>(Query().equal("id", parent->id()));
            if (current) {
                current->_data["hMsgId"] = mid;
                current->_data["references"] = refs;
                current->_data["rthMsgId"] = irt;
                current->_data["headerMessageIdGenerated"] = false;
                if (smarterMail) current->_data["smHydratedV1"] = true;
                store->save(current.get());
            }
            transaction.commit();
        }
    }
    if (mid.empty()) throw SyncException("reply-headers-unavailable", "The original message ID is unavailable. Refresh the original message before replying; no email was sent.", false);
    auto chain = mailcore::Array::array();
    std::set<std::string> seen;
    auto append = [&](const std::string & raw) {
        const auto id = canonical(raw);
        if (!id.empty() && id != mid && seen.insert(id).second)
            chain->addObject(mailcore::String::stringWithUTF8Characters(id.c_str()));
    };
    if (refs.is_array()) for (const auto & ref : refs) if (ref.is_string()) append(ref.get<std::string>());
    if (chain->count() == 0) append(irt); // RFC 5322 fallback when parent has no References
    chain->addObject(mailcore::String::stringWithUTF8Characters(mid.c_str()));
    outgoing->setReferences(chain);
    outgoing->setInReplyTo(mailcore::Array::arrayWithObject(mailcore::String::stringWithUTF8Characters(mid.c_str())));
}
}
